version: '3'

networks:
  nginx-php82:

services:

  #nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php82-service
    networks:
      - nginx-php82

  #php
  php82-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php82-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nginx-php82
